### ISSUE TITLE
political positions

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#5] opened 2018-07-12 15:59 UTC
http://wnpt.brlcloud.com/wn/synset?id=00585810-n

1. This synset for minister has as ancestor the synsets http://wnpt.brlcloud.com/wn/synset?id=00023100-n and http://wnpt.brlcloud.com/wn/synset?id=00002137-n.

2. We also have http://wnpt.brlcloud.com/wn/synset?id=10320863-n , maybe duplicated?

3. On the other hand, http://wnpt.brlcloud.com/wn/synset?id=10140314-n (governor), http://wnpt.brlcloud.com/wn/synset?id=10303814-n (mayor) are both under http://wnpt.brlcloud.com/wn/synset?id=00007846-n (individual) and http://wnpt.brlcloud.com/wn/synset?id=00001930-n (physical_entity).

Does it make sense? Can we uniform that? Does anyone have already worked on that domain? If so, references?

Kind of related to it? Recent discussion in the mailing list by Christiane Fellbaum:

> Roles: I have discussed extensively with professional philosophers who warned me that they thought covering Roles exhaustively would be an impossible task. It's easy enough for profession nouns (student, teacher) or relations (parents, niece) and some hand-picked cases like "pet," but difficult in many other cases. One could use a stiletto heel or a nail clipper as weapon, for example, though that is not as common as a knife-as-a-weapon. So we've stayed away from it for now. But maybe we can discuss some time in the future.

**Comment by jmccrae** [comment] 2018-07-13 11:10
Hi Alexandre,
So the proposal it to remove `00585810-n` (`ewn-00586847-n`) in the file `noun.act.xml` as a duplicate of `10320863-n` (`ewn-10340521-n`) in the file `noun.person.xml`?

Given the very different locations of these two concepts in the noun hierarchy it seems to me that they  are not obviously duplicates. Further any significant restructuring of the hierarchy is not in the scope of this project for the moment. As such, I will close this issue for the time being, although it is something that with more input we could reopen as part of a wider issue.

By the way, as an example of the kind of duplicates we are looking at for 3.2 consider
http://wnpt.brlcloud.com/wn/synset?id=11103648-n
http://wnpt.brlcloud.com/wn/synset?id=11095587-n

**Closed by jmccrae** 2018-07-13 11:10 UTC
Labels: synset-duplicate
