### ISSUE TITLE
sunburns aren't brown

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#128] opened 2019-02-08 11:42 UTC
14314036-n (Interlingual Index: i112055)
(n) burn, sunburn, suntan, tan 
> a browning of the skin resulting from exposure to the rays of the sun

sunburns aren't generally brown

**Comment by jmccrae** [comment] 2020-01-12 11:13
Proposal: remove 'sunburn' from this synset

**Comment by arademaker** [comment] 2020-01-12 21:16
the verb `burn` has many senses... some of them could be merged. Same for at least two senses of the noun `burn`. But this is another issue maybe...

**Comment by arademaker** [comment] 2020-01-12 21:17
why not just rewrite the gloss

> a damage the skin resulting from exposure to the rays of the sun

**Comment by jmccrae** [comment] 2020-01-13 12:47
There is a synset already for the meaning of damage to the skin.

`ewn-14313867-n`  (Interlingual Index: i112054)
(n) sunburn, erythema solare 
> redness of the skin caused by exposure to the rays of the sun

Here we are talking about (cosmetic) browning.

**Comment by jmccrae** [comment] 2020-01-13 12:49
On the verb 'burn'. Yes, there are many sense distinctions that are subtle and also don't make much sense to me. I would propose we first solve #243 and then return to some of these very common verbs.

**Comment by arademaker** [comment] 2020-03-16 18:05
We have already sunburn at `redness of the skin caused by exposure to the rays of the sun`

**Comment by jmccrae** [comment] 2020-03-17 11:43
I take that as agreement and made the PR

**Closed** 2020-03-30 15:20 UTC
Labels: PR created, synset member
