### ISSUE TITLE
Verb frames 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#139] opened 2019-04-03 11:59 UTC
https://wordnet.princeton.edu/documentation/wninput5wn

I never really understood the verb frames completely. The syntax of the templates is not explained and it seems inconsistent for me. How do you instantiate them here?

**Comment by jmccrae** [comment] 2019-04-03 12:24
Verb frames are handled through the `SyntacticBehaviour` tag, here is an example

```xml
    <LexicalEntry id="ewn-partake-v">
      <Lemma writtenForm="partake" partOfSpeech="v"/>
      <Form writtenForm="partaken"/>
      <Form writtenForm="partook"/>
      <Sense id="ewn-partake-v-01174998-01" n="2" synset="ewn-01174998-v" dc:identifier="partake%2:34:13::"/>
      <SyntacticBehaviour subcategorizationFrame="The banks %s the check" senses="ewn-partake-v-02300169-01"/>
      <SyntacticBehaviour subcategorizationFrame="They %s the car down the avenue" senses="ewn-partake-v-02742535-01"/>
      <SyntacticBehaviour subcategorizationFrame="The coins %s " senses="ewn-partake-v-01174998-01 ewn-partake-v-02300169-01"/>
    </LexicalEntry>
```

Simply put the verb is supposed to replace the `%s` and the senses indicate which senses of the verb use this frame

**Comment by jmccrae** [comment] 2021-07-14 14:36
Duplicate of #244 (I believe @arademaker reopen this issue if I am wrong)

**Closed by jmccrae** 2021-07-14 14:36 UTC
Labels: help wanted
