### ISSUE TITLE
sense ordering?

### ISSUE THREAD

**Issue by odanoburu** [globalwordnet/english-wordnet#33] opened 2018-11-26 16:16 UTC
hi, I can't seem to find the ordering sense in the XML format. for instance, if we look up the word [`dog`](http://wordnetweb.princeton.edu/perl/webwn?c=7&sub=Change&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&i=-1&h=00000000&s=dog) on PWN, I get that the most common sense for `dog` is that of the domestic animal. 

the XML format has the information of which words are most common in a given synset -- this ranking being `-04` part in `ewn-dog-n-09905672-04` -- but not which senses are most common for a given word, right? or have I overlooked something? cc @jmccrae @hmuniz

**Comment by jmccrae** [comment] 2018-11-26 17:06
Yes, the issue is that the words are now separated by lexicographer files so they don't combine correctly in the merge script. I will add a fix for this. 

Personally, I wouldn't use this data though, see https://wordnet.princeton.edu/frequently-asked-questions

> How are the senses in WordNet ordered?
> WordNet senses are ordered using sparse data from semantically tagged text. The order of the senses is given simply so that some of the most common uses are listed above others (and those for which there is no data are randomly ordered). The sense numbers and ordering of senses in WordNet should be considered random for research purposes.

**Comment by odanoburu** [comment] 2018-11-26 17:11
thank you!

yes, I absolutely agree that this data is unreliable.

**Comment by daikinomura** [comment] 2018-11-27 00:47
Hi odanoburu .

Probably you are looking for frequency data.  I am not sure whether It is included in this XML file or not...
Its in a "cntlist" of PWN's datafile. For example:

>grep " dog%" cntlist
42 dog%1:05:00:: 1
2 dog%2:38:00:: 1

The details of cntlist is in https://wordnet.princeton.edu/documentation/cntlist5wn. Tagged data has 2 dogs.  dog%1:05:00:: is the noun dog of domestic animal and other is verb. There are many other "dog"s in WordNet but they don't appear in the cntlist because they haven't tagged so far.

I wonder "cntlist" will help you or not.( They could be too small for you)
At least, you may be able to get the dog of domestic animal with "cntlist".

**Comment by odanoburu** [comment] 2018-11-27 00:57
yes, I think so @daikinomura !

but now I'm more convinced I should deviate from the WSD algorithm I was implementing and ignore these. I knew the data sparsity would be a problem, but I didn't know that

> The sense numbers and ordering of senses in WordNet should be considered random for research purposes.

as @jmccrae quoted. so maybe I should close this? thank you both for the help!

**Comment by fcbond** [comment] 2018-11-27 01:47
In fact, I can't find the citation off hand, but first listed sense
does much better than random, and most frequent sense, even with these
low counts, is even better, it should be the baseline you measure
against.
On Tue, Nov 27, 2018 at 8:57 AM bruno cuconato <notifications@github.com> wrote:
>
> yes, I think so @daikinomura !
>
> but now I'm more convinced I should deviate from the WSD algorithm I was implementing and ignore these. I knew the data sparsity would be a problem, but I didn't know that
>
> The sense numbers and ordering of senses in WordNet should be considered random for research purposes.
>
> as @jmccrae quoted. so maybe I should close this? thank you both for the help!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Francis Bond <http://www3.ntu.edu.sg/home/fcbond/>
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Closed** 2018-11-27 14:34 UTC
Labels: bug

**Comment by jmccrae** [comment] 2018-11-27 14:35
Sense ordering may be of little use but it is still best not to discard it. 

Perhaps as discussed in #31 it would be best to store the entries independently of the synsets so this can be handled better.

**Comment by odanoburu** [comment] 2018-11-27 14:42
@fcbond I think I read this somewhere too, but I just thought that this was because the experiment was done against a general domain corpus (maybe even SemCor itself?). I don't think this performance would hold if the test corpus were of a specific domain.

thanks @jmccrae !
