### ISSUE TITLE
Incorrect usage of wn:partOfSpeech according to the WordNet schema

### ISSUE THREAD

**Issue by simongray** [globalwordnet/english-wordnet#922] opened 2023-05-30 14:16 UTC
**Release format**
RDF

**Describe the bug**
According to the WordNet schema, the domain of `wn:partOfSpeech` is supposed to be `ontolex:LexicalEntry` yet in the published TTL file, this relation is applied using `ontolex:LexicalConcept` as the domain, e.g. http://wordnet-rdf.princeton.edu/id/oewn-06094057-n.

This seems to imply that `ontolex:LexicalConcept` (a synset) and `ontolex:LexicalEntry` (a word) are equivalent classes, yet they are clearly distinct in the published Ontolex standard.

**To Reproduce**
1. Find any `ontolex:LexicalConcept` in the published WordNet TTL file.
2. Note that the `wn:partOfSpeech` attribute is likely present.
3. Compare with the WordNet schema which states:

```turtle

:partOfSpeech a owl:ObjectProperty ;
  rdfs:domain ontolex:LexicalEntry ;
  rdfs:range :PartOfSpeech ;
  rdfs:label "part of speech"@en ;
  rdfs:comment "The syntactic class of the entry, e.g., noun, verb"@en .
```

**Expected behavior**
I would only expect this relation to be defined for an `ontolex:LexicalEntry`, e.g. http://localhost:3456/dannet/external/enl/chemical_science%23chemical_science-n.

**Comment by jmccrae** [comment] 2023-05-30 14:28
Seems to be a duplicate of this issue: https://github.com/globalwordnet/schemas/issues/67

That is fixed, but it seems that the default link for the WordNet ontology is still v1.1, I have updated this and this should solve the issue

**Closed by jmccrae** 2023-05-30 14:28 UTC
Labels: release format
